"""Public launcher; the desktop application's MCP implementation stays in its installer.

When the Stochastly desktop app is installed, this launcher hands over to the MCP server that ships
inside it. When it is not, the launcher still lists the same tools (names, descriptions, input
schemas and annotations, read from `stochastly_mcp_data/tools_manifest.json`, which is generated
from the real server), and every call returns a structured answer saying the desktop app is
required. This package contains no engine code.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import runpy
import sys
from typing import Any

PRICING_URL = "https://stochastly.com/pricing"
MANIFEST = Path(__file__).resolve().parent / "stochastly_mcp_data" / "tools_manifest.json"
FALLBACK_NOTE = (
    "Requires the Stochastly desktop app: this tool runs inside the app, which is not installed on "
    "this machine. Install it from " + PRICING_URL + ", open it and activate a licence."
)


def installed_script() -> Path:
    override = os.environ.get("STOCHASTLY_MCP_SCRIPT")
    if override:
        return Path(override).expanduser()
    if sys.platform == "win32":
        return Path(os.environ.get("LOCALAPPDATA", "")) / "Stochastly" / "mcp" / "stochastly_mcp.py"
    if sys.platform == "darwin":
        return Path("/Applications/Stochastly.app/Contents/Resources/mcp/stochastly_mcp.py")
    return Path("/opt/stochastly/mcp/stochastly_mcp.py")


def load_manifest(path: Path = MANIFEST) -> dict[str, Any]:
    """The tool definitions of the real server, as generated by the app's build."""
    data = json.loads(path.read_text(encoding="utf-8"))
    tools = data.get("tools")
    if not isinstance(tools, list) or not tools:
        raise ValueError(f"{path}: no tools in the manifest")
    return data


def fallback_tools(manifest: dict[str, Any]) -> list[dict[str, Any]]:
    """Manifest tools with the desktop-app requirement stated first in each description."""
    out = []
    for tool in manifest["tools"]:
        item = dict(tool)
        item["description"] = FALLBACK_NOTE + "\n\n" + str(tool.get("description") or "")
        out.append(item)
    return out


def editions_label(needed: str) -> str:
    """'atelier or portfolio' -> 'Atelier or Portfolio'."""
    return " or ".join(part.strip().capitalize() for part in needed.split(" or "))


def refusal(name: str, manifest: dict[str, Any]) -> dict[str, Any]:
    """The structured answer every tool returns while the desktop app is missing."""
    editions = manifest.get("editions") or {}
    needed = (editions.get("per_tool") or {}).get(name) or editions.get("default") or "atelier or portfolio"
    known = {t.get("name") for t in manifest["tools"]}
    return {
        "ok": False,
        "tool": name,
        "known_tool": name in known,
        "app_installed": False,
        "error": (f"'{name}' requires the Stochastly desktop app, which is not installed on this "
                  f"machine. Install it from {PRICING_URL}, open it and activate a licence; "
                  f"this tool needs the {editions_label(needed)} edition."),
        "needed": needed,
        "pricing": PRICING_URL,
    }


def serve_fallback() -> None:
    import anyio
    import mcp.types as types
    from mcp.server.lowlevel import Server
    from mcp.server.stdio import stdio_server

    try:
        manifest = load_manifest()
    except (OSError, ValueError) as exc:
        # A broken install must still explain itself rather than crash the client's MCP list.
        manifest = {"tools": [{
            "name": "app_info",
            "description": "Explain how to install and license Stochastly before using its MCP tools. "
                           f"(The tool manifest could not be read: {exc})",
            "inputSchema": {"type": "object", "properties": {}},
        }]}
    tools = [types.Tool(**t) for t in fallback_tools(manifest)]
    server = Server("stochastly")

    @server.list_tools()
    async def _list_tools() -> list[types.Tool]:
        return tools

    # Input is not validated: whatever the arguments, the honest answer is the same refusal.
    @server.call_tool(validate_input=False)
    async def _call_tool(name: str, arguments: dict[str, Any]) -> dict[str, Any]:
        return refusal(name, manifest)

    async def _run() -> None:
        async with stdio_server() as (read, write):
            await server.run(read, write, server.create_initialization_options())

    anyio.run(_run)


def main() -> None:
    script = installed_script()
    if script.is_file():
        # Execute the installed client. Its existing server owns all tools, the loopback
        # connection, and the fail-closed licence gate. The public wheel contains none of it.
        sys.argv = [str(script)]
        runpy.run_path(str(script), run_name="__main__")
        return
    serve_fallback()


if __name__ == "__main__":
    main()
